### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by MarkTiedemann** [garethr/kubeval#55]
`kubeval v0.7.0` produces a panic when validating below file:

```
# test.yml
kind:
```

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/garethr/kubeval/kubeval.validateResource(0xc420088d80, 0x5, 0x205, 0x7ffc6055df6f, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/garethr/kubeval/kubeval/kubeval.go:131 +0x9fd
github.com/garethr/kubeval/kubeval.Validate(0xc420088d80, 0x5, 0x205, 0x7ffc6055df6f, 0x11, 0x0, 0x0, 0x0, 0xc4200cb900, 0x0)
        /go/src/github.com/garethr/kubeval/kubeval/kubeval.go:174 +0x1e9
github.com/garethr/kubeval/cmd.glob..func1(0xa94160, 0xc420112e40, 0x1, 0x1)
        /go/src/github.com/garethr/kubeval/cmd/root.go:67 +0x1f6
github.com/garethr/kubeval/vendor/github.com/spf13/cobra.(*Command).execute(0xa94160, 0xc42000c110, 0x1, 0x1, 0xa94160, 0xc42000c110)
        /go/src/github.com/garethr/kubeval/vendor/github.com/spf13/cobra/command.go:654 +0x299
github.com/garethr/kubeval/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa94160, 0xc4200cb680, 0x0, 0x0)
        /go/src/github.com/garethr/kubeval/vendor/github.com/spf13/cobra/command.go:729 +0x339
github.com/garethr/kubeval/vendor/github.com/spf13/cobra.(*Command).Execute(0xa94160, 0x0, 0x6e)
        /go/src/github.com/garethr/kubeval/vendor/github.com/spf13/cobra/command.go:688 +0x2b
github.com/garethr/kubeval/cmd.Execute()
        /go/src/github.com/garethr/kubeval/cmd/root.go:99 +0x31
main.main()
        /go/src/github.com/garethr/kubeval/main.go:6 +0x20
```

**Comment by garethr** [comment]
Ah, thanks for the simple test case. I'll get this fixed. Much appreciated.

**Comment by garethr** [comment]
Thanks for reporting. I've fixed this in master (https://github.com/garethr/kubeval/commit/50ced2637e6309b176a6fd76897108d1d2d43c8a) and this will be in the next release.
